#+TITLE: Materiály k předmětu „Fyzika máločásticových jaderných systémů“ (NJSF157), ÚČJF MFF UK, zimní semestr 2024/2025

Poslední úprava: [2025-01-09 Thu]

* Literatura (prozatím, odkazy na konrétní kapitoly níže)

- [Gl] W. Glöckle, The quantum mechanical few-body problem
- [Ta] J. R. Taylor, The quantum theory of nonrelativistic collisions
- [Ne] R. G. Newton, Scattering theory of waves and particles (celkem rigorózní)
- Ručně psané poznámky (t4-t13_poznamky.pdf)

* Týden 1

Úvodní

- Předběžný sylabus
- Co by koho zajímalo?

* Týden 2

Máločásticové jaderné systémy - prezentace (t2.prezentace.pdf)

* Týden 3

Exotické jaderné systémy - prezentace (t3.prezentace.pdf)

* Týden 4

Základní pojmy teorie rozptylu: Møllerovy vlnové operátory, stacionární rozptylové stavy

- Poznámky k přednášce: strany 1 - 5
- Doma přečíst: kapitolu 1.1 v [Gl]

* Týden 5

Základní pojmy teorie rozptylu (pokrač.): Lippmann-Schwingerova rovnice; rezolventy; elementy T, S, K matice

- Poznámky k přednášce: strany 5 - 11
- Doma přečíst: kapitoly 1.2 - 1.5 v [Gl]

* Týden 6

NN systém: spin, izospin, parciální vlny

- Poznámky k přednášce: strany 12 - 16
- Doma přečíst: kapitoly 2.1 - 2.4 v [Gl] (+ 7-a, 7-b v [Ta])

* Týden 7

NN systém: spin, izospin, parciální vlny (pokrač.)

- Poznámky k přednášce: 17 - 20
- Doma přečíst: kapitoly 2.5 - 2.6 v [Gl]

* Týden 8

NN systém: spin, izospin, parciální vlny (pokrač.)
- Poznámky k přednášce: 21 - 25
- 

* Týden 9

Schrödingerova a Lippmannova-Schwingerova rovnice pro NN v parciálních vlnách. Potenciály v souřadnicové a impulsové reprezentaci, lokální/nelokální. Bornova/Neumannova řada pro T operátor.

- Poznámky k přednášce: 26 - 29

* Týden 10

Příklady řešení Schrödingerovy a Lippmannovy-Schwingerovy rovnice. Separabilní potenciály, delta potenciál v 1D, efektivní teorie.

- Poznámky k přednášce: 30 - 34

* Týden 11

Příklady řešení Schrödingerovy a Lippmannovy-Schwingerovy rovnice. (pokrač.) Efektivní teorie: delta potenciál v 1D.

- Poznámky k přednášce: 35 - 37

* Týden 12

Příklady řešení Schrödingerovy a Lippmannovy-Schwingerovy rovnice. (pokrač.)

- Efektivní teorie: delta potenciál 1D -> 3D, regularizace, renormalizace.
- Numerické řešení Lippmannovy-Schwingerovy rovnice v p-reprezentaci.
- Poznámky k přednášce: 38 - 42; článek Haftel & Tabakhin; složka Numerika

* Týden 13

Příklady řešení Schrödingerovy a Lippmannovy-Schwingerovy rovnice. (pokrač.)

Numerické řešení Schrödingerovy rovnice v x-reprezentaci.

* Co se nestihlo - literatura

** (TBA) NN interakce, pionless EFT
** (TBA) NN interakce, chirální EFT
** Systémy s několika nukleony
- Rozptyl: Faddeev a Faddeev-Yakubovsky [Gl, kap. 3 a 4]
- Variační metody pro vázané stavy: No-core shell model, SVM [NCSM.pdf, Barnea.pdf]
